#!/bin/bash
cmd="$@"
qemu-system-aarch64 \
    -M virt \
    -machine virtualization=true \
    -machine type=virt \
    -cpu cortex-a72 \
    -smp 4 \
    -kernel /root/zImage-arm64be \
    -initrd /root/initramfs-arm64be.img \
    -append "earlyprintk=serial,ttyAMA0 console=ttyAMA0 coredump_filter=0x3f FRIDA_INJECT=$FRIDA_INJECT cmd=\"$cmd\"" \
    -m 4096M \
    -net nic,id=eth \
    -net user,id=mynet,net=192.168.76.0/24 \
    -virtfs local,path=/home/share/,mount_tag=host0,security_model=passthrough,id=host0 \
    -virtfs local,path=/home/ws/,mount_tag=host1,security_model=passthrough,id=host1 \
    -nographic \
    -no-reboot