#!/bin/bash
cmd="$@"
qemu-system-x86_64 \
    -smp 4 \
    -kernel /root/bzImage-x64 \
    -initrd /root/initramfs-x64.img \
    -append "earlyprintk=serial,ttyS0 console=ttyS0 coredump_filter=0x3f FRIDA_INJECT=$FRIDA_INJECT cmd=\"$cmd\"" \
    -m 4096M \
    -net nic,id=eth \
    -net user,id=mynet,net=192.168.76.0/24 \
    -virtfs local,path=/home/share/,mount_tag=host0,security_model=passthrough,id=host0 \
    -virtfs local,path=/home/ws/,mount_tag=host1,security_model=passthrough,id=host1 \
    -nographic \
    -no-reboot